# Generated by Django 4.2.17 on 2024-12-16 19:53

import django.core.files.storage
from django.db import migrations, models
import pathlib
import shop.apps.seller.abstract_models
import shop.apps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Shop Name')),
                ('handle', models.SlugField(max_length=20, unique=True, verbose_name='Shop Handle')),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[shop.apps.user.models.validate_length(15)], verbose_name='GSTIN Number')),
                ('gstin_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='GSTIN verified by Admin')),
                ('gstin_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/arun/Projects/zite69/protected')), upload_to=shop.apps.seller.abstract_models.gstin_upload_path, verbose_name='Photo or scan of GSTIN')),
                ('gstin_file_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Photo or scan of GSTIN has been verified by Admin')),
                ('pan', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[shop.apps.user.models.validate_length(10)], verbose_name='PAN Number')),
                ('pan_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='PAN Number verified by Admin')),
                ('pan_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/arun/Projects/zite69/protected')), upload_to=shop.apps.seller.abstract_models.pan_upload_path, verbose_name='Photo or scan of PAN card')),
                ('pan_file_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Photo or scan of PAN card verified by Admin')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
