# Generated by Django 4.2.17 on 2024-12-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shipping_preference',
            field=models.CharField(blank=True, choices=[('S', 'Self Shipping'), ('Z', 'zite69 Shipping (coming soon)')], default='S', max_length=1, verbose_name='Shipping Preference'),
        ),
    ]
