# Generated by Django 4.2.17 on 2024-12-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_shipping_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reasons'),
        ),
    ]
