# Generated by Django 5.1.8 on 2025-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_approval_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='accept_terms',
            field=models.BooleanField(default=False, verbose_name='Accept Terms'),
        ),
        migrations.AddField(
            model_name='seller',
            name='read_terms',
            field=models.BooleanField(default=False, verbose_name='Read Terms'),
        ),
    ]
