# Generated by Django 5.2.12 on 2026-03-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shiprocketorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiprocketorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
