# Generated by Django 4.2.18 on 2025-01-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_approval_notes'),
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='sellers',
            field=models.ManyToManyField(related_name='partners', to='seller.seller'),
        ),
    ]
