# Generated by Django 4.2.16 on 2024-10-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20241031_0524'),
        ('partner', '0007_partner_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='seller',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='Seller'),
        ),
    ]
