# Generated by Django 5.1.8 on 2025-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_product_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qc_status',
            field=models.CharField(choices=[('NOT', 'Not Submitted'), ('SUB', 'Submitted'), ('APP', 'Approved')], default='NOT', max_length=3),
        ),
    ]
