# Generated by Django 5.2.3 on 2025-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_product_qc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Code can be used to store a secondary unique identifier, when upc isn't sufficient"),
        ),
    ]
