# Generated by Django 5.2.12 on 2026-03-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_product_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryHierarchy',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product category hierarchy',
                'verbose_name_plural': 'Product categories hierarchy',
                'db_table': 'catalogue_product_category_hierarchy',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='exclude_from_menu',
            field=models.BooleanField(db_index=True, default=False, help_text='Exclude this category from the menu.', verbose_name='Exclude from menu'),
        ),
        migrations.AddField(
            model_name='category',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Long description'),
        ),
    ]
