# Generated by Django 4.2.17 on 2024-12-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAddesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Address?')),
                ('shipping', models.BooleanField(default=False, verbose_name='Shipping Address?')),
                ('pickup', models.BooleanField(default=False, verbose_name='Pickup Address for Sellers')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.useraddress')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
