# Generated by Django 4.2.16 on 2024-10-27 05:50

from django.db import migrations, models
import localflavor.in_.models
import shop.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profileaddesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Seller or CEO level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=shop.apps.user.models.upload_profile_photo_path, verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan',
            field=localflavor.in_.models.INPANCardNumberField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[shop.apps.user.models.validate_length(10)], verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller'), ('C', 'CEO')], db_index=True, max_length=4, verbose_name='User Profile Type'),
        ),
    ]
