# Generated by Django 4.2.16 on 2024-10-27 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_level_profile_photo_alter_profile_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pan',
            field=localflavor.in_.models.INPANCardNumberField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
