# Generated by Django 4.2.20 on 2025-03-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(default='https://www.zite69.com/static/img/generic-profile.png', verbose_name='Avatar URL'),
        ),
    ]
