# Generated by Django 4.2.16 on 2024-10-31 17:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_pan_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IN', unique=True, verbose_name='Phone Number'),
        ),
    ]
