# Generated by Django 4.2.16 on 2024-11-04 00:03

from django.db import migrations, models
import localflavor.in_.models
import shop.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_unique_profile_gstin_ifnotnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gstin',
            field=models.CharField(db_index=True, default=None, max_length=15, null=True, unique=True, validators=[shop.apps.user.models.validate_length(15)], verbose_name='GSTIN Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan',
            field=localflavor.in_.models.INPANCardNumberField(db_index=True, default=None, max_length=10, null=True, unique=True, verbose_name='PAN Number'),
        ),
    ]
