# Generated by Django 4.2.16 on 2024-10-27 05:52
from django.db import migrations
from django.conf import settings
from localflavor.in_.in_states import STATE_CHOICES
import csv
import gzip

#Some states are given different names in the csv file
#Here we map them to the appropirate State name
MAP_TO_STATE = {
    'Daman and Diu': 'Dadra and Nagar Haveli and Daman and Diu',
    'Pondicherry': 'Puducherry',
    'Andaman and Nico.In.': 'Andaman and Nicobar Islands',
    'Dadra and Nagar Hav.': 'Dadra and Nagar Haveli and Daman and Diu',
    'Chattisgarh': 'Chhattisgarh',
    'Megalaya': 'Meghalaya'
}

def load_initial_data(apps, schema_editor):
    State = apps.get_model('main', 'State')
    Pincode = apps.get_model('main', 'Pincode')

    for k, v in STATE_CHOICES:
        State.objects.create(code=k, name=v)

    with gzip.open(settings.BASE_DIR / 'data/Pincode_30052019.csv.gz', 'rt', encoding='windows-1252') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            try:
                state = State.objects.get(name=MAP_TO_STATE.get(row[-1], row[-1]))
            except State.DoesNotExist:
                print(f"Unable to find state: {row[-1]}")
                continue
            Pincode.objects.create(office=row[3], pincode=row[4],state=state)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
