# Generated by Django 4.2.16 on 2024-10-31 18:07

from django.db import migrations
from django.conf import settings
from django.utils.text import slugify
import string
import random

def generate_password(length=10):
    #Generate a random password of specified length after remvoing confusing characters
    #like l and O and 0 and 1
    characters = string.ascii_letters.replace('l', '').replace('O', '') + string.digits.replace('0', '').replace('1', '')
    return "".join(random.choice(characters) for i in range(length))

def create_default_data(apps, schema_editor):
    # User = apps.get_model('user', 'User')
    # Seller = apps.get_model('seller', 'Seller')
    Site = apps.get_model('sites', 'Site')
    #Create default system user
    #Create seller tied to the system user
    # system = User.objects.get(id=settings.ZITE69_MAIN_USER_ID)
    # Seller.objects.create(
    #     name = settings.ZITE69_MAIN_SELLER,
    #     handle = slugify(settings.ZITE69_MAIN_SELLER)[:20],
    #     user = system
    # ) 

    Site.objects.create(
        domain = settings.ZITE69_MAIN_DOMAIN,
        name = 'Main Zite69 Website' + ('-dev' if settings.DEBUG else '')
    )

    Site.objects.create(
        domain = settings.ZITE69_SELLER_DOMAIN,
        name = 'Seller Zite69 Website' + ('-dev' if settings.DEBUG else '')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20241027_0552'),
        ('user', '0006_create_defaults'),
    ]

    operations = [
        migrations.RunPython(create_default_data)
    ]
