# Generated by Django 4.2.16 on 2024-12-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('main', '0003_createdefaultdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pincode',
            new_name='Postoffice',
        ),
        migrations.RenameIndex(
            model_name='postoffice',
            new_name='main_postof_office_19ef1f_idx',
            old_name='main_pincod_office_5393ac_idx',
        ),
    ]
