# Generated by Django 4.2.17 on 2024-12-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import shop.apps.zitepayment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0007_organizationaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Account Holder Name')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Account')),
                ('bank', models.CharField(db_index=True, max_length=128, verbose_name='Bank Name')),
                ('branch', models.CharField(max_length=128, verbose_name='Branch Name')),
                ('account_type', models.CharField(choices=[('S', 'Savings Account'), ('C', 'Current Account'), ('O', 'Other')], max_length=2, verbose_name='Account Type')),
                ('imps', models.BooleanField(default=False, verbose_name='IMPS Available')),
                ('rtgs', models.BooleanField(default=False, verbose_name='RTGS Available')),
                ('neft', models.BooleanField(default=False, verbose_name='NEFT Available')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IN', verbose_name='Bank Contact')),
                ('ifsc', models.CharField(db_index=True, max_length=11, verbose_name='IFSC Code')),
                ('micr', models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name='MICR')),
                ('swift', models.CharField(blank=True, db_index=True, max_length=11, null=True, validators=[shop.apps.zitepayment.models.validate_swift], verbose_name='SWIFT')),
                ('account_number', models.CharField(db_index=True, max_length=18, verbose_name='Account Number')),
                ('registered_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='IN', verbose_name='Registered Mobile Number')),
                ('branch_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.organizationaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bank', 'account_number')},
            },
        ),
    ]
