# Generated by Django 5.1.9 on 2025-05-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_product_qc_status'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('cmsplugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProductCollection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=32, verbose_name='Collection Name')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=32, null=True, verbose_name='Label')),
                ('label_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='Label Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='FeaturedProducts',
        ),
    ]
