# Generated by Django 5.2.12 on 2026-03-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugins', '0002_featuredproductcollection_featuredproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='label_type',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('best', 'Bestseller'), ('new', 'New'), ('sale', 'Sale')], max_length=8, null=True, verbose_name='Label Type'),
        ),
    ]
