# Generated by Django 4.2.16 on 2024-11-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, null=True, region='IN', verbose_name='Phone Number')),
                ('invite_type', models.CharField(choices=[('S', 'Invite Seller'), ('C', 'Invite CEO')], db_index=True, default='S', max_length=1, verbose_name='Invite Type')),
                ('local_url', models.URLField(verbose_name='Local path to handle invitation')),
                ('configuration', models.JSONField(null=True, verbose_name='Invitation Configuration')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(related_name='invitations', to='auth.permission')),
            ],
            options={
                'permissions': [('invite_seller', 'Invite someone to become a Premium Seller using their email address and/or phonenumber'), ('invite_ceo', 'Invite someone to become a CEO (Community Exchange Officer) of the site')],
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Invitation Code')),
                ('expiry', models.DateTimeField(null=True, verbose_name='Expiry Date')),
                ('sent_on', models.DateTimeField(null=True, verbose_name='Sent On')),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, verbose_name='Email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, null=True, region='IN', verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('S', 'Invite Sent'), ('A', 'Invite Accepted'), ('I', 'Invite Not Used')], db_index=True, default='S', max_length=1, verbose_name='Invitation Code Status')),
                ('short_url', models.URLField(db_index=True, unique=True, verbose_name='Shortened URL')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='invitation.invitation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
