# Generated by Django 4.2.17 on 2024-12-16 19:53

import django.core.files.storage
from django.db import migrations, models
import phonenumber_field.modelfields
import shop.apps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Service Name')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='uploads/sellerreg/%Y/%m/%d', verbose_name='Product Image')),
            ],
        ),
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Full Name')),
                ('shop_name', models.CharField(max_length=128, verbose_name='Shop Name')),
                ('shop_handle', models.SlugField(max_length=20, verbose_name='Shop Handle')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email Adderss')),
                ('gst_status', models.CharField(choices=[('Y', 'I have GST'), ('N', "I don't have GST"), ('E', 'I am expemted'), ('L', 'I will add later')], db_index=True, default='Y', max_length=2, verbose_name='GST Status')),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[shop.apps.user.models.validate_length(15)], verbose_name='GSTIN Number')),
                ('gstin_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='GSTIN Verified by Admin')),
                ('pan', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[shop.apps.user.models.validate_length(10)], verbose_name='PAN Number')),
                ('pan_verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='PAN Number verified by Admin')),
                ('approved_on', models.DateTimeField(null=True, verbose_name='Approved On')),
                ('approval_notes', models.TextField(blank=True, null=True, verbose_name='Approval/Rejection Reasons')),
                ('approval_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('T', 'Temporarily Rejected'), ('R', 'Rejected'), ('I', 'Inprogress')], db_index=True, default='I', max_length=2, verbose_name='Approval Status')),
            ],
        ),
    ]
