# Generated by Django 4.2.16 on 2024-10-27 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import shop.apps.registration.models
import shop.apps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Full Name')),
                ('shop_name', models.CharField(max_length=128, verbose_name='Shop Name')),
                ('shop_handle', models.SlugField(max_length=20, verbose_name='Shop Handle')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, validators=[shop.apps.registration.models.unique_in_db(shop.apps.user.models.User, 'phone')], verbose_name='Phone Number')),
                ('email', models.EmailField(db_index=True, max_length=254, validators=[shop.apps.registration.models.unique_in_db(shop.apps.user.models.User, 'email')], verbose_name='Email Adderss')),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, validators=[shop.apps.user.models.validate_length(15), shop.apps.registration.models.unique_in_db(shop.apps.user.models.Profile, 'gstin')], verbose_name='GSTIN Number')),
                ('pan', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[shop.apps.user.models.validate_length(10), shop.apps.registration.models.unique_in_db(shop.apps.user.models.Profile, 'pan')], verbose_name='PAN Number')),
                ('approved_on', models.DateTimeField(null=True, verbose_name='Approved On')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sellers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='uploads/sellerreg/%Y/%m/%d', verbose_name='Product Image')),
                ('seller_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.sellerregistration')),
            ],
        ),
    ]
