# Generated by Django 4.2.16 on 2024-10-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20241027_0552'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistration',
            name='pincode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.pincode'),
            preserve_default=False,
        ),
    ]
