# Generated by Django 4.2.16 on 2024-12-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerregistration',
            old_name='pincode',
            new_name='postoffice',
        ),
    ]
