# Generated by Django 4.2.17 on 2024-12-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistration',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerregistration',
            name='postoffice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.postoffice'),
        ),
        migrations.AddField(
            model_name='sellerregistration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='seller_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.sellerregistration'),
        ),
        migrations.AddConstraint(
            model_name='sellerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('gstin', ''), _negated=True), ('gstin__isnull', False)), fields=('gstin',), name='unique_gstin_ifnotnull'),
        ),
        migrations.AddConstraint(
            model_name='sellerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('pan', ''), _negated=True), ('pan__isnull', False)), fields=('pan',), name='unique_pan_insellerreg_ifnotnull'),
        ),
    ]
