# Generated by Django 4.2.17 on 2024-12-24 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_sellerregistrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
