# Generated by Django 4.2.16 on 2024-10-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20241027_0552'),
        ('registration', '0003_sellerregistration_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='pincode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.pincode'),
        ),
    ]
