# Generated by Django 4.2.16 on 2024-10-30 16:09

from django.db import migrations, models
import shop.apps.registration.models
import shop.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_sellerregistration_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True, validators=[shop.apps.user.models.validate_length(15), shop.apps.registration.models.unique_in_db(shop.apps.user.models.Profile, 'gstin')], verbose_name='GSTIN Number'),
        ),
    ]
