# Generated by Django 4.2.16 on 2024-10-31 04:32

from django.db import migrations, models
import shop.apps.registration.models
import shop.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_sellerregistration_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='pan',
            field=models.CharField(db_index=True, max_length=10, null=True, unique=True, validators=[shop.apps.user.models.validate_length(10), shop.apps.registration.models.unique_in_db(shop.apps.user.models.Profile, 'pan')], verbose_name='PAN Number'),
        ),
    ]
