# Generated by Django 4.2.16 on 2024-11-03 19:25

from django.db import migrations, models
import shop.apps.registration.models
import shop.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_sellerregistration_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='gstin',
            field=models.CharField(db_index=True, max_length=15, null=True, validators=[shop.apps.user.models.validate_length(15), shop.apps.registration.models.unique_in_db(shop.apps.user.models.Profile, 'gstin')], verbose_name='GSTIN Number'),
        ),
        migrations.AddConstraint(
            model_name='sellerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('gstin',), name='unique_gstin_ifnotnull'),
        ),
    ]
