# Generated by Django 4.2.16 on 2024-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_sellerregistration_gstin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sellerregistration',
            name='unique_gstin_ifnotnull',
        ),
        migrations.AddConstraint(
            model_name='sellerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('gstin', ''), _negated=True), ('gstin__isnull', False)), fields=('gstin',), name='unique_gstin_ifnotnull'),
        ),
    ]
