# Generated by Django 4.2.16 on 2024-11-04 03:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_sellerregistration_unique_gstin_ifnotnull_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/uploads/sellerreg'), upload_to='uploads/sellerreg/%Y/%m/%d', verbose_name='Product Image'),
        ),
    ]
