# Generated by Django 4.2.16 on 2024-11-04 08:11

from django.db import migrations, models
import shop.apps.registration.models
import shop.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_sellerproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregistration',
            name='pan',
            field=models.CharField(db_index=True, max_length=10, null=True, validators=[shop.apps.user.models.validate_length(10), shop.apps.registration.models.unique_in_db(shop.apps.user.models.Profile, 'pan')], verbose_name='PAN Number'),
        ),
        migrations.AddConstraint(
            model_name='sellerregistration',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('pan', ''), _negated=True), ('pan__isnull', False)), fields=('pan',), name='unique_pan_insellerreg_ifnotnull'),
        ),
    ]
