# Generated by Django 4.2.16 on 2024-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_sellerregistration_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Service Name'),
        ),
    ]
